FROM node:18-alpine

#Create a app directory
WORKDIR /app

#Install app dependencies
COPY package*.json ./

#Run npm install
RUN npm install

#Bundle app souce
COPY . .

EXPOSE 3978

CMD [ "npm", "start" ]


# docker build . -t lenabe/bot-node-app
# docker run -d --name bot -p 3978:3978 lenabe/bot-node-app